const ActionType = {
    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCEED: 'GET_USERS_SUCCEED',
    GET_USERS_FAILED: 'GET_USERS_FAILED',
    ADD_USERS: 'ADD_USERS',
    ADD_USERS_SUCCEED: 'ADD_USERS_SUCCEED',
    ADD_USERS_FAILED: 'ADD_USERS_FAILED',
    UPDATE_USERS: 'UPDATE_USERS',
    UPDATE_USERS_SUCCEED: 'UPDATE_USERS_SUCCEED',
    UPDATE_USERS_FAILED: 'UPDATE_USERS_FAILED',
    DEL_USERS: 'DEL_USERS',
    DEL_USERS_SUCCEED: 'DEL_USERS_SUCCEED',
    DEL_USERS_FAILED: 'DEL_USERS_FAILED'
}

export default ActionType;
